---

dovecot_config:
  listen:
    - "127.0.0.1"

dovecot_master: {}

dovecot_logging:
  auth_debug: true
  auth_debug_passwords: true
  auth_verbose: true
  # false, plain, sha1
  auth_verbose_passwords: plain
  debug_log_path: /var/log/dovecot/debug.log
  mail_debug: true

dovecot_mail:
  mail_uid: 1101
  mail_gid: 1101
  mail_attachment_hash: "%{sha1:120}"
  mail_home: /var/vmail/%d/%n
  mail_location: maildir:~/
  # mail_plugins: </etc/dovecot/mail_plugins
  mail_attachment_fs: "crypt:set_prefix=mail_crypt_global:posix:"
  mail_attachment_dir: /var/attachments
  mail_attachment_min_size: 128k

  first_valid_uid: 1101
  last_valid_uid: 1101
  first_valid_gid: 1101
  last_valid_gid: 1101

  namespaces:
    - type: private
      name: inbox
      separator: "."
      prefix: INBOX.
      inbox: true
      list: true
      subscriptions: true
      location: "maildir:%h:INDEX=/srv/mail/INDEX/%d/%n:CONTROL=/srv/mail/CONTROL/%d/%n:LAYOUT=maildir++"

    - type: public
      separator: "."
      prefix: shared.
      location: "maildir:/srv/mail/PUBLIC:INDEX=/srv/mail/PUBLIC/indexes:CONTROL=/srv/mail/PUBLIC/control:LAYOUT=maildir++"
      list: children
      subscriptions: true

    - type: shared
      seperator: "."
      prefix: "shared.%%u."
      location: "maildir:%%h:INDEX=~/Shared/%%u"
      list: children
      subscriptions: false

dovecot_auth:
  disable_plaintext_auth: true

dovecot_acl:
  plugins:
    - acl: vfile:/etc/dovecot/global-acls:cache_secs=300
    - acl_shared_dict: file:/srv/mail/%d/shared-mailboxes.db

# Database related

dovecot_authentications:
  - sql:
      passdb:
        driver: sql
        args: /etc/dovecot/dovecot-sql.conf.ext
      userdb:
        driver: sql
        args: /etc/dovecot/dovecot-sql.conf.ext

dovecot_sql:
  driver: mysql
  connects:
    host: database
    dbname: postfix
    user: postfix
    password: postfix
  default_pass_scheme: CRAM-MD5
  password_query: >
    SELECT
      password
      FROM mailbox
      WHERE username = '%u'
  user_query: >
    SELECT
      '/srv/mail/%d/%n' as home,
      CONCAT('maildir:/srv/mail/', maildir) AS mail,
      1101 AS uid,
      1101 AS gid
      FROM mailbox
      WHERE username = '%u'

dovecot_dict_sql:
  connects:
    host: database
    dbname: postfix
    user: postfix
    password: postfix
  maps:
    - pattern: priv/quota/storage
      table: quota
      username_field: username
      value_field: bytes
    - pattern: priv/quota/messages
      table: quota
      username_field: username
      value_field: messages
    - pattern: "shared/expire/$user/$mailbox"
      table: expires
      value_field: expire_stamp
      fields:
        username: $user
        mailbox: $mailbox

...
