---

- name: create logging directory
  file:
    state: directory
    path: "{{ dovecot_logging_directory }}"
    mode: 0755

- name: create dovecot.conf
  template:
    src: etc/dovecot/dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    backup: true
    mode: 0644

- name: create splitted configurations
  template:
    src: etc/dovecot/conf.d/{{ item }}.j2
    dest: /etc/dovecot/conf.d/{{ item }}
    backup: true
    mode: 0644
  loop:
    # - 10-auth.conf
    # - 10-director.conf
    # - 10-logging.conf
    # - 10-mail.conf
    # - 10-master.conf
    # - 10-ssl.conf
    # - 10-tcpwrapper.conf
    - 15-lda.conf
...
