---

- name: include OS specific configuration
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian
        - "{{ ansible_os_family | lower }}.yml"
        - default.yml
      skip: true

- name: detect docker environment
  set_fact:
    is_docker_guest: "{{
      ansible_virtualization_role | default('host') == 'guest' and
      ansible_virtualization_type | default('none') == 'docker' }}"

- name: update package cache
  package:
    update_cache: true

- name: install dependencies
  package:
    name: "{{ dovecot_dependencies }}"
    state: present

- name: gathering facts now
  setup:



- name: merge dovecot config configuration between defaults and custom
  set_fact:
    dovecot_config: "{{ dovecot_defaults_config |
      combine( dovecot_config, recursive=True ) }}"

# - name: merge dovecot auth configuration between defaults and custom
#   set_fact:
#     dovecot_auth: "{{ dovecot_defaults_auth |
#       combine( dovecot_auth, recursive=True ) }}"
#
# - name: merge dovecot director configuration between defaults and custom
#   set_fact:
#     dovecot_director: "{{ dovecot_defaults_director |
#       combine( dovecot_director, recursive=True ) }}"
#
# - name: merge dovecot logging configuration between defaults and custom
#   set_fact:
#     dovecot_logging: "{{ dovecot_defaults_logging |
#       combine( dovecot_logging, recursive=True ) }}"
#
# - name: merge dovecot mail configuration between defaults and custom
#   set_fact:
#     dovecot_mail: "{{ dovecot_defaults_mail |
#       combine( dovecot_mail, recursive=True ) }}"
#
# - name: merge dovecot master configuration between defaults and custom
#   set_fact:
#     dovecot_master: "{{ dovecot_defaults_master |
#       combine( dovecot_master, recursive=True ) }}"
#
# - name: merge dovecot ssl configuration between defaults and custom
#   set_fact:
#     dovecot_ssl: "{{ dovecot_defaults_ssl |
#       combine( dovecot_ssl, recursive=True ) }}"
#
# - name: merge dovecot tcpwrapper configuration between defaults and custom
#   set_fact:
#     dovecot_tcpwrapper: "{{ dovecot_defaults_tcpwrapper |
#       combine( dovecot_tcpwrapper, recursive=True ) }}"
#
# - name: merge dovecot lda configuration between defaults and custom
#   set_fact:
#     dovecot_lda: "{{ dovecot_defaults_lda |
#       combine( dovecot_lda, recursive=True ) }}"

- name: merge dovecot mailboxes configuration between defaults and custom
  set_fact:
    dovecot_mailboxes: "{{ dovecot_defaults_mailboxes |
      combine( dovecot_mailboxes, recursive=True ) }}"

- name: merge dovecot imap configuration between defaults and custom
  set_fact:
    dovecot_imap: "{{ dovecot_defaults_imap |
      combine( dovecot_imap, recursive=True ) }}"

# - name: merge dovecot lmtp configuration between defaults and custom
#   set_fact:
#     dovecot_lmtp: "{{ dovecot_defaults_lmtp |
#       combine( dovecot_lmtp, recursive=True ) }}"
#
# - name: merge dovecot managesieve configuration between defaults and custom
#   set_fact:
#     dovecot_managesieve: "{{ dovecot_defaults_managesieve |
#       combine( dovecot_managesieve, recursive=True ) }}"
#
# - name: merge dovecot pop3 configuration between defaults and custom
#   set_fact:
#     dovecot_pop3: "{{ dovecot_defaults_pop3 |
#       combine( dovecot_pop3, recursive=True ) }}"
#
# - name: merge dovecot submission configuration between defaults and custom
#   set_fact:
#     dovecot_submission: "{{ dovecot_defaults_submission |
#       combine( dovecot_submission, recursive=True ) }}"
#
# - name: merge dovecot acl configuration between defaults and custom
#   set_fact:
#     dovecot_acl: "{{ dovecot_defaults_acl |
#       combine( dovecot_acl, recursive=True ) }}"
#
# - name: merge dovecot plugin configuration between defaults and custom
#   set_fact:
#     dovecot_plugin: "{{ dovecot_defaults_plugin |
#       combine( dovecot_plugin, recursive=True ) }}"
#
# - name: merge dovecot quota configuration between defaults and custom
#   set_fact:
#     dovecot_quota: "{{ dovecot_defaults_quota |
#       combine( dovecot_quota, recursive=True ) }}"
#
# - name: merge dovecot sieve extprograms configuration between defaults and custom
#   set_fact:
#     dovecot_sieve_extprograms: "{{ dovecot_defaults_sieve_extprograms |
#       combine( dovecot_sieve_extprograms, recursive=True ) }}"
#
# - name: merge dovecot sieve configuration between defaults and custom
#   set_fact:
#     dovecot_sieve: "{{ dovecot_defaults_sieve |
#       combine( dovecot_sieve, recursive=True ) }}"
#
# - name: merge dovecot authentications configuration between defaults and custom
#   set_fact:
#     dovecot_authentications: "{{ dovecot_defaults_authentications |
#       combine( dovecot_authentications, recursive=True ) }}"
#
# - name: merge dovecot dict auth configuration between defaults and custom
#   set_fact:
#     dovecot_dict_auth: "{{ dovecot_defaults_dict_auth |
#       combine( dovecot_dict_auth, recursive=True ) }}"
#
# - name: merge dovecot dict sql configuration between defaults and custom
#   set_fact:
#     dovecot_dict_sql: "{{ dovecot_defaults_dict_sql |
#       combine( dovecot_dict_sql, recursive=True ) }}"
#
# - name: merge dovecot ldap configuration between defaults and custom
#   set_fact:
#     dovecot_ldap: "{{ dovecot_defaults_ldap |
#       combine( dovecot_ldap, recursive=True ) }}"
#
# - name: merge dovecot sql configuration between defaults and custom
#   set_fact:
#     dovecot_sql: "{{ dovecot_defaults_sql |
#       combine( dovecot_sql, recursive=True ) }}"

...
