---

- name: start and enable service
  service:
    name: dovecot
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - dovecot
    - dovecot-start-enable-service

...
