---

- name: start and enable service
  ansible.builtin.service:
    name: dovecot
    state: "{{ dovecot_service_state | default('started') }}"
    enabled: "{{ dovecot_service_enabled | default(true) | bool }}"
  tags:
    - configuration
    - dovecot
    - dovecot-start-enable-service

...
