---

dovecot_config:
  listen:
    - "127.0.0.1"

dovecot_mail:
  namespaces:
    - type: private
      name: inbox
      separator: "."
      prefix: INBOX.
      inbox: true
      list: true
      subscriptions: true
      location: "maildir:%h:INDEX=/srv/mail/INDEX/%d/%n:CONTROL=/srv/mail/CONTROL/%d/%n:LAYOUT=maildir++"

    - type: public
      separator: "."
      prefix: shared.
      location: "maildir:/srv/mail/PUBLIC:INDEX=/srv/mail/PUBLIC/indexes:CONTROL=/srv/mail/PUBLIC/control:LAYOUT=maildir++"
      list: children
      subscriptions: true

  mail_uid: 1101
  mail_gid: 1101
  first_valid_uid: 1101
  last_valid_uid: 1101
  first_valid_gid: 1101
  last_valid_gid: 1101

  mail_attachment_fs: sis-queue posix
  mail_attachment_hash: "%{sha1:120}"

dovecot_lmtp:
  # proxy: false
  # save_to_detail_mailbox: false
  # rcpt_check_quota: false
  # hdr_delivery_address: final
  protocols:
    - lmtp:
        mail_plugins: $mail_plugins

dovecot_tcpwrapper:
  login_access_sockets: tcpwrap
  services:
    - login/tcpwrap:
        listeners:
          - login/tcpwrap:
              type: "unix"
              mode: "0666"
              user: ""
              group: ""

dovecot_managesieve:
  service_count: 1
  process_min_avail: 0
  vsz_limit: 64M
  # protocols:
  #    - $protocols
  #    - sieve
  # service managesieve-login {
    #inet_listener sieve {
    #}
    #inet_listener sieve_deprecated {
    #}
    #service_count: 1
    #process_min_avail: 0
    #vsz_limit: 64M
  #}
  services:
    - managesieve-login:
        # chroot: login
        # client_limit: 0
        # drop_priv_before_exec: no
        # executable: managesieve-login
        # extra_groups: ""
        # group: ""
        # idle_kill: 0
        listeners:
        - sieve:
            type: inet
            port: 4190
            address: ""
            haproxy: false
            reuse_port: false
            ssl: false
        - sieve_deprecated:
            type: inet
            port: 2000



  protocols:
    - sieve:
        managesieve_max_line_length: 65536
        mail_max_userip_connections: 10
        mail_plugins: []
        #
        # MANAGESIEVE logout format string:
        #  %i - total number of bytes read from client
        #  %o - total number of bytes sent to client
        #  %{put_bytes} - Number of bytes saved using PUTSCRIPT command
        #  %{put_count} - Number of scripts saved using PUTSCRIPT command
        #  %{get_bytes} - Number of bytes read using GETCRIPT command
        #  %{get_count} - Number of scripts read using GETSCRIPT command
        #  %{get_bytes} - Number of bytes processed using CHECKSCRIPT command
        #  %{get_count} - Number of scripts checked using CHECKSCRIPT command
        #  %{deleted_count} - Number of scripts deleted using DELETESCRIPT command
        #  %{renamed_count} - Number of scripts renamed using RENAMESCRIPT command
        managesieve_logout_format:
          - "bytes: %i/%o"
          - "deleted: %{deleted_count}"
          - "renamed: %{renamed_count}"
        managesieve_implementation_string: Dovecot Pigeonhole
        managesieve_sieve_capability: ""
        managesieve_notify_capability: ""
        managesieve_max_compile_errors: 5

dovecot_pop3:
  # no_flag_updates: false
  # enable_last: false
  # reuse_xuidl: false
  # lock_session: false
  # fast_size_lookups: false
  #
  #
  #  %v - Mailbox's IMAP UIDVALIDITY
  #  %u - Mail's IMAP UID
  #  %m - MD5 sum of the mailbox headers in hex (mbox only)
  #  %f - filename (maildir only)
  #  %g - Mail's GUID
  #  UW's ipop3d         : %08Xv%08Xu
  #  Courier             : %f or %v-%u (both might be used simultaneously)
  #  Cyrus (<= 2.1.3)    : %u
  #  Cyrus (>= 2.1.4)    : %v.%u
  #  Dovecot v0.99.x     : %v.%u
  #  tpop3d              : %Mf
  # uidl_format: %08Xu%08Xv
  # save_uidl: false
  #
  #   allow: Show duplicates to clients.
  #   rename: Append a temporary -2, -3, etc. counter after the UIDL.
  # uidl_duplicates: allow
  # deleted_flag: ""
  #
  #  %i - total number of bytes read from client
  #  %o - total number of bytes sent to client
  #  %t - number of TOP commands
  #  %p - number of bytes sent to client as a result of TOP command
  #  %r - number of RETR commands
  #  %b - number of bytes sent to client as a result of RETR command
  #  %d - number of deleted messages
  #  %{deleted_bytes} - number of bytes in deleted messages
  #  %m - number of messages (before deletion)
  #  %s - mailbox size in bytes (before deletion)
  #  %u - old/new UIDL hash. may help finding out if UIDLs changed unexpectedly
  # logout_format: "top=%t/%p, retr=%r/%b, del=%d/%m, size=%s"
  #
  #   outlook-no-nuls:
  #     Outlook and Outlook Express hang if mails contain NUL characters.
  #     This setting replaces them with 0x80 character.
  #   oe-ns-eoh:
  #     Outlook Express and Netscape Mail breaks if end of headers-line is
  #     missing. This option simply sends it if it's missing.
  # The list is space-separated.
  # client_workarounds: []
  protocols:
    - pop3:
        #mail_plugins: $mail_plugin
        mail_max_userip_connections: 10

dovecot_submission:
  #submission_logout_format: in=%i out=%o
  #hostname: ""
  #submission_max_mail_size: ""
  #submission_max_recipients: ""
  #submission_client_workarounds: ""
  #submission_relay_host: ""
  #submission_relay_port: 25
  #submission_relay_trusted: false
  #submission_relay_user: ""
  #submission_relay_master_user: ""
  #submission_relay_password: ""
  #submission_relay_ssl: false
  #submission_relay_ssl_verify: true
  #submission_relay_rawlog_dir: ""
  protocols:
    - submission:  {}
        #mail_plugins: $mail_plugin
        #mail_max_userip_connections: 10

...
